Vagrant.configure(2) do |config|
	config.vm.define "electroneum-poc" do |devbox2|
	config.vm.synced_folder "~/DevOps/electroneum-poc","/home/vagrant/electroneum-poc"
	config.vm.synced_folder "~/.aws/dhd","/home/vagrant/.aws"
	  devbox2.vm.box = "ubuntu/bionic64"
	  devbox2.vm.network "private_network", ip: "192.168.199.10"
		devbox2.vm.hostname = "electroneum-poc"
		devbox2.vm.provision "shell", path: "scripts/install.sh"
		devbox2.vm.provision "shell", path: "scripts/cron.sh"
		devbox2.vm.provider "virtualbox" do |v|
                        # set timesync parameters to keep the clocks better in sync
                        # sync time every 10 seconds
                        v.customize [ "guestproperty", "set", :id, "/v/GuestAdd/VBoxService/--timesync-interval", 10000 ]
                        # adjustments if drift > 100 ms
                        v.customize [ "guestproperty", "set", :id, "/v/GuestAdd/VBoxService/--timesync-min-adjust", 100 ]
                        # sync time on restore
                        v.customize [ "guestproperty", "set", :id, "/v/GuestAdd/VBoxService/--timesync-set-on-restore", 1 ]
                        # sync time on start
                        v.customize [ "guestproperty", "set", :id, "/v/GuestAdd/VBoxService/--timesync-set-start", 1 ]
                        # at 1 second drift, the time will be set and not "smoothly" adjusted
                        v.customize [ "guestproperty", "set", :id, "/v/GuestAdd/VBoxService/--timesync-set-threshold", 1000 ]
			v.memory = 4096
			v.cpus = 2
		end
	end
end
