Vagrant.configure(2) do |config|
	config.vm.define "devops-box" do |xenial64|
       # config.vm.synced_folder "~/DevOps","/home/vagrant/DevOps"
		xenial64.vm.box = "ubuntu/xenial64"
		#xenial64.vm.network "private_network", ip: "192.168.199.9"
		xenial64.vm.hostname = "devops-box-xenial64"
		xenial64.vm.provision "shell", path: "scripts/install.sh"
		xenial64.vm.provider "virtualbox" do |v|
			v.memory = 4096
			v.cpus = 2
		end
	end
end
